language: node_js
node_js:
- stable
install: npm install
services:
- postgresql
before_script:
- npm run db:create:test
script: npm test
after_success: npm run coverage
deploy:
  provider: heroku
  api_key:
    secure: Uy7ohQlEG7r5GD4huecKb7gBWdKAYuuqXR2IVk7+/X/YhNDmIw0mCwp75S6SAGifRrkJx6GpVBm5APgqZ4CmAvNNuCsa8TGFB/sLo4Xrx5hzz2Ki+UJIVoumdPz90vfayVCYpocA8Sz/7zjCnJugVfThQWmQiP0Az20XJzUAgPKnL1rdvfAG5HOM6flZwc+Se9rJACFsaKgY1ga/idai0f4O1lbEil/IMoDthMgzDFl5tdPlmTSzmiczvZ3j/+PI0RA/Vu3RsK3HpWcGuutSQRTttsqn5cLLxhYvTqfFUube0eWZGDAXyIkTsG9n2y8pP94oc+45XG4fxE5JD5Or3oMd4Coai9xZUoQDF0A0z4PVoawjXszfRth+lkPxga9xGP8wSgBS0uWVQCCfFr62wYH+OJSpJiXdi6KPKUXoJqdfN4jtKAXuC12cq43xGVhpopBRNvpM+t3QJbLEmLyEmjcXcRHSLK8G2J6Td9oyeclyq57x5TDE9ISWhJVNZiiWFFqas9YxJ+clfy06yFHeiHjb3qXd+hCMXOqwg+6gG9j/EXFuBLfgBWMxJ9tQWVM1rlOvaamob0yP9LmBdy73boqTkGHISLDMX1ZTDj2nMn1lhLQQguJh8T7CoodF8dCKTHbO4nlj3JutL9pmPuDdzlVGK3LgiK3rwCnFyt/xubU=
  app: traviswearscoveralls
  on:
    repo: JordanCruzCorrea/express-api-ci
