language: node_js
node_js:
- stable
install: npm install
services:
- postgresql
before_script:
- npm run db:create:test
script: npm test
after_success: npm run coverage
deploy:
  provider: heroku
  api_key:
    secure: V3xis0MU6yPdlv6Z4P7wwAZ/xeEhkLUC4qXVmS3ZbT2p0DSD+mjfLVZc615kjS4Q/PqVenf4e2DaAO3C6yX5j5ADH1BzWy9eamrXXJPz6AVQEB6j8+CDZYnbkkpG4SLZaGfWvS0swQUo19timEMRLgKpbdVMt4ZgwAMmVdm79Bk/EyYmTHiS81epl+6p0QGw+Xc8owMt1WA6Q0qw9zm5Miums0ory4bp0ISvQmZ8ExZo0arIa7BORNnWjVHAwVD8dynHJ1Gxp5lzLp2hSSSOOJ6ucalLu4MaJXaGqeEKyuGYrluqS+07KRLR85KOeoij4vsDmk0cfHluxkN/fw7jn5+VB0Z7JRADbNJ2DPIIcSLE9us8OJdzJv75FLbcB682MIA6XstOXUYQWGRSNJ/oCoxdHFCVzmrkJshFzBo/T6cAPGiAQIZqIOEyPTAYvZXs05dhKAshevaY9vGEzRlIxJdjhgURDBv/scy1yCjSLOxPiBTbkyLu/TuBJd/Darhfr7BuW7V8vbp7/Mc4LRxsgbOJw9L115cVTPMoRU9UDHcXev+BkKcNTGgbmsikg+CCZbl9tyuwFMapfVEt7sIBX7M+vbhINnmw3aC66Q9wfnO8lwwZcBKm0/Aw2RBMcAHXIcFg7+Zdrwm9WRZZvr8RiJt+ckNDPmsFWxi7snjyYNc=
  app: traviswearscoveralls
  on:
    repo: JordanCruzCorrea/express-api-ci
